routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\AdminMiddleware;
use App\Http\Controllers\GuestBookController;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/show/{id}', 'HomeController@show')->name('home.show');

Route::get('/guest-book', 'GuestBookController@index')->name('guest-book');
Route::get('/guest-book/create', 'GuestBookController@create')->name('guest-book.create');
Route::post('/guest-book/store', 'GuestBookController@store')->name('guest-book.store');

Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => AdminMiddleware::class
],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/news', 'NewsController', ['except' => ['show']]);
        Route::resource('/categories', 'NewsCategoryController', ['except' => ['show']]);
        Route::resource(
            '/guest-book',
            'GuestBookController',
            [
                'except' => [
                    'create',
                    'store',
                    'show',
                ],
            ]
        );
    }
);

resources/views/admin/_footer.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: box
 * Date: 15/02/18
 * Time: 13:00
 */
?>

<footer class="sticky-footer">
    <div class="container">
        <div class="text-center">
            <small>Copyright © Your Website 2018</small>
        </div>
    </div>
</footer>

resources/views/admin/_notification-menu.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: box
 * Date: 15/02/18
 * Time: 13:12
 */
?>

<ul class="navbar-nav ml-auto">
    {{--<li class="nav-item dropdown">--}}
        {{--<a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
            {{--<i class="fa fa-fw fa-envelope"></i>--}}
            {{--<span class="d-lg-none">Messages--}}
              {{--<span class="badge badge-pill badge-primary">12 New</span>--}}
            {{--</span>--}}
            {{--<span class="indicator text-primary d-none d-lg-block">--}}
              {{--<i class="fa fa-fw fa-circle"></i>--}}
            {{--</span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu" aria-labelledby="messagesDropdown">--}}
            {{--<h6 class="dropdown-header">New Messages:</h6>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
                {{--<strong>David Miller</strong>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">Hey there! This new--}}
                    {{--version of SB Admin is pretty awesome! These messages clip off when they--}}
                    {{--reach the end of the box so they don't overflow over to the sides!</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
                {{--<strong>Jane Smith</strong>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
                {{--<strong>John Doe</strong>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">I've sent the final--}}
                    {{--files over to you for review. When you're able to sign off of them let--}}
                    {{--me know and we can discuss distribution.</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item small" href="#">View all messages</a>--}}
        {{--</div>--}}
    {{--</li>--}}
    {{--<li class="nav-item dropdown">--}}
        {{--<a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">--}}
            {{--<i class="fa fa-fw fa-bell"></i>--}}
            {{--<span class="d-lg-none">Alerts--}}
              {{--<span class="badge badge-pill badge-warning">6 New</span>--}}
            {{--</span>--}}
            {{--<span class="indicator text-warning d-none d-lg-block">--}}
              {{--<i class="fa fa-fw fa-circle"></i>--}}
            {{--</span>--}}
        {{--</a>--}}
        {{--<div class="dropdown-menu" aria-labelledby="alertsDropdown">--}}
            {{--<h6 class="dropdown-header">New Alerts:</h6>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
              {{--<span class="text-success">--}}
                {{--<strong>--}}
                  {{--<i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>--}}
              {{--</span>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">This is an automated server response message. All systems are online.</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
              {{--<span class="text-danger">--}}
                {{--<strong>--}}
                  {{--<i class="fa fa-long-arrow-down fa-fw"></i>Status Update</strong>--}}
              {{--</span>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">This is an automated server response message. All systems are online.</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item" href="#">--}}
              {{--<span class="text-success">--}}
                {{--<strong>--}}
                  {{--<i class="fa fa-long-arrow-up fa-fw"></i>Status Update</strong>--}}
              {{--</span>--}}
                {{--<span class="small float-right text-muted">11:21 AM</span>--}}
                {{--<div class="dropdown-message small">This is an automated server response message. All systems are online.</div>--}}
            {{--</a>--}}
            {{--<div class="dropdown-divider"></div>--}}
            {{--<a class="dropdown-item small" href="#">View all alerts</a>--}}
        {{--</div>--}}
    {{--</li>--}}
    {{--<li class="nav-item">--}}
        {{--<form class="form-inline my-2 my-lg-0 mr-lg-2">--}}
            {{--<div class="input-group">--}}
                {{--<input class="form-control" placeholder="Поиск..." type="text">--}}
                {{--<span class="input-group-append">--}}
                {{--<button class="btn btn-primary" type="button">--}}
                  {{--<i class="fa fa-search"></i>--}}
                {{--</button>--}}
              {{--</span>--}}
            {{--</div>--}}
        {{--</form>--}}
    {{--</li>--}}
    <li class="nav-item">
        {!! Form::open(['method' => 'POST', 'route' => 'logout']) !!}
        {{ Form::button('<i class="fa fa-sign-out">Выйти</i>', [
        'type' => 'submit',
         'class' => 'btn btn-default',
         'onClick' => 'return confirm("Вы уверены?")'
         ]) }}
        {!! Form::close() !!}
    </li>

</ul>

resources/views/admin/_sidebar.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: box
 * Date: 15/02/18
 * Time: 13:00
 */
?>

<ul class="navbar-nav navbar-sidenav">
    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
        <a class="nav-link" href="/">
            <i class="fa fa-fw fa-home"></i>
            <span class="nav-link-text">На главную</span>
        </a>
    </li>
    <li class="nav-item {{ Route::currentRouteNamed('news.*') ? 'active' : '' }}" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
        <a class="nav-link" href="{{ route('news.index') }}">
            <i class="fa fa-fw fa-newspaper-o"></i>
            <span class="nav-link-text">Новости</span>
        </a>
    </li>
    <li class="nav-item {{ Route::currentRouteNamed('categories.*') ? 'active' : '' }}" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
        <a class="nav-link" href="{{ route('categories.index') }}">
            <i class="fa fa-fw fa-list"></i>
            <span class="nav-link-text">Категории новостей</span>
        </a>
    </li>
    <li class="nav-item {{ Route::currentRouteNamed('guest-book.*') ? 'active' : '' }}" data-toggle="tooltip" data-placement="right" title="" data-original-title="Dashboard">
        <a class="nav-link" href="{{ route('guest-book.index') }}">
            <i class="fa fa-fw fa-book"></i>
            <span class="nav-link-text">Гостевая книга</span>
        </a>
    </li>
</ul>

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
    <ol class="breadcrumb">
        <li class="breadcrumb-item">
            <a href="#">Админка</a>
        </li>
        <li class="breadcrumb-item active">Панель приборов</li>
    </ol>
    <div class="card">
        <div class="card-header">
            <i class="fa fa-area-chart"></i> Статистика</div>
        <div class="card-body">
        </div>
        <div class="card-footer small text-muted"></div>
    </div>
@endsection

resources/views/admin/layout.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'name') }}</title>
    <link href="{{ asset('css/admin/font-awesome.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/admin/sb-admin.css') }}" rel="stylesheet" type="text/css">
    <link href="{{ asset('css/admin/bootstrap.css') }}" rel="stylesheet" type="text/css">
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
    <a class="navbar-brand" href="{{ route('dashboard') }}">Админка</a>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
            data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
        @include('admin._sidebar')
        <ul class="navbar-nav sidenav-toggler">
            <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                    <i class="fa fa-fw fa-angle-left"></i>
                </a>
            </li>
        </ul>
        @include('admin._notification-menu')
    </div>
</nav>
<div class="content-wrapper">
    <div class="container-fluid">
        @yield('content')
    </div>
    @include('admin._footer')
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>
</div>
<script src="{{ asset('js/admin/jquery.js') }}"></script>
<script src="{{ asset('js/admin/jquery_002.js') }}"></script>
<script src="{{ asset('js/admin/sb-admin.js') }}"></script>
<script src="{{ asset('js/admin/bootstrap.js') }}"></script>
</body>
</html>