routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use App\Http\Middleware\AdminMiddleware;
use App\Http\Controllers\GuestBookController;

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@index');
Route::get('/show/{id}', 'HomeController@show')->name('home.show');

Route::get('/guest-book', 'GuestBookController@index')->name('guest-book');
Route::get('/guest-book/create', 'GuestBookController@create')->name('guest-book.create');
Route::post('/guest-book/store', 'GuestBookController@store')->name('guest-book.store');

Route::get('/get_captcha/{config?}', function (\Mews\Captcha\Captcha $captcha, $config = 'default') {
    return $captcha->src($config);
});

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => AdminMiddleware::class
],
    function () {
        Route::get('/', 'DashboardController@index')->name('dashboard');
        Route::resource('/news', 'NewsController', ['except' => ['show']]);
        Route::resource('/categories', 'NewsCategoryController', ['except' => ['show']]);
        Route::resource(
            '/guest-book',
            'GuestBookController',
            [
                'except' => [
                    'create',
                    'store',
                    'show',
                ],
            ]
        );
    }
);

resources/views/admin/categories/create.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Boiko Sergii
 * Date: 17.02.2018
 * Time: 22:33
 */

/** @var \Illuminate\Support\MessageBag $errors */
?>
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('dashboard') }}">Админка</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ route('categories.index') }}">Категории новостей</a>
            </li>
            <li class="breadcrumb-item active">Создать</li>
        </ol>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                Добавление категории
            </div>
            <div class="card-body">
                <div class="box">
                    {!! Form::open(['route' => 'categories.store']) !!}
                    <div class="box-body">
                        <div class="col-md-12">
                            @include('input-validation', [
                            'attribute' => 'title',
                            'label' => 'Имя категории',
                            'input' => Form::input('text', 'title', old('title'), [
                                'class' => 'form-control',
                                'placeholder' => 'Введите название категории новостей',
                                ]),
                            ])
                            <label>
                                <strong>
                                    Скрыть категорию из списка?
                                </strong>
                                {!!
                                Form::hidden('is_hidden', \App\Models\NewsCategory::IS_VISIBLE)
                                 . Form::checkbox('is_hidden', \App\Models\NewsCategory::IS_HIDDEN, old('is_hidden'))
                                !!}
                            </label>
                        </div>
                    </div>
                    <div class="box-footer">
                        <a href="{{ route('categories.index') }}" class="btn btn-default">Назад</a>
                        {!! Form::submit('Добавить', ['class' => 'btn btn-success']) !!}
                    </div>
                </div>
            </div>
        </div>
        {!! Form::close() !!}
    </section>
@endsection

resources/views/admin/categories/edit.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: Boiko Sergii
 * Date: 18.02.2018
 * Time: 3:13
 */

/** @var \App\Models\NewsCategory $category */
?>

@extends('admin.layout')
@section('content')
    <section class="content-header">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('dashboard') }}">Админка</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{{ route('categories.index') }}">Категории новостей</a>
            </li>
            <li class="breadcrumb-item active">Создать</li>
        </ol>
    </section>
    <section class="content">
        <div class="card">
            <div class="card-header">
                Редактирование категории
            </div>
            <div class="card-body">
                <div class="box">
                    {!! Form::open(['route' => ['categories.update', $category], 'method' => 'put']) !!}
                    <div class="box-body">
                        <div class="col-md-12">
                            @include('input-validation', [
                            'attribute' => 'title',
                            'label' => 'Имя категории',
                            'input' => Form::input('text', 'title', $category->title, [
                                'class' => 'form-control',
                                'placeholder' => 'Введите название категории новостей',
                                ]),
                            ])
                            <label>
                                <strong>
                                    Скрыть категорию из списка?
                                </strong>
                                {!!
                                Form::hidden('is_hidden', \App\Models\NewsCategory::IS_VISIBLE)
                                 . Form::checkbox('is_hidden', \App\Models\NewsCategory::IS_HIDDEN, $category->is_hidden)
                                !!}
                            </label>
                        </div>
                    </div>
                    <div class="box-footer">
                        <a href="{{ route('categories.index') }}" class="btn btn-default">Назад</a>
                        {!! Form::submit('Изменить', ['class' => 'btn btn-primary']) !!}
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </section>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layout')
@section('content')
    <section class="content-header">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{{ route('dashboard') }}">Админка</a>
            </li>
            <li class="breadcrumb-item active">Категории новостей</li>
        </ol>
    </section>
    @if(session()->has('message'))
        <p class="alert {{ session()->get('alert') }}">{{ session()->get('message') }}</p>
    @endif
    <section class="content">
        <div class="card">
            <div class="card-header">
                Список категорий новостей
            </div>
            <div class="card-body">
                <div class="box">
                    <div class="box-body">
                        <div class="form-group">
                            <a href="{{ route('categories.create') }}" class="btn btn-success">Добавить</a>
                        </div>
                        {{ $categories->links() }}
                        <table class="table table-bordered table-striped">
                            <thead>
                            <tr>
                                <th></th>
                                <th class="col-md-11">Имя категории</th>
                                <th>Действия</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($categories as $category)
                                <tr>
                                    <td>
                                        <i class="fa fa-eye {!! $category->isVisible() ? 'text-success' : 'text-danger' !!}"></i>
                                    </td>
                                    <td>{{ $category->title }}</td>
                                    <td>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['categories.destroy', $category->id]]) !!}
                                        <a href="{{ route('categories.edit', $category->id) }}"
                                           class="fa fa-pencil"></a>
                                        {{ Form::button('<i class="fa fa-remove text-danger"></i>', [
                                        'type' => 'submit',
                                         'class' => 'btn btn-link',
                                         'onClick' => 'return confirm("Вы уверены?")'
                                         ]) }}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $categories->links() }}
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection